//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constraintsforeigenworkerne
    {
        public int confidd { get; set; }
        public int iddayw { get; set; }
    
        public virtual days_of_wor days_of_wor { get; set; }
    }
}
