//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constraintsforeigenworker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constraintsforeigenworker()
        {
            this.days_of_wor = new HashSet<days_of_wor>();
            this.days_of_wor2 = new HashSet<days_of_wor2>();
            this.Foreign_worker = new HashSet<Foreign_worker>();
        }
    
        public int confid { get; set; }
        public Nullable<double> age_of_o { get; set; }
        public string languagefw { get; set; }
        public string gender { get; set; }
        public int idcity { get; set; }
        public string addressfg { get; set; }
        public Nullable<int> Level_of_functioningfg { get; set; }
        public Nullable<double> money_of_hour { get; set; }
        public Nullable<long> passwardwor { get; set; }
        public string mail { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<days_of_wor> days_of_wor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<days_of_wor2> days_of_wor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foreign_worker> Foreign_worker { get; set; }
    }
}
