//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constraintsold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constraintsold()
        {
            this.days_of_old = new HashSet<days_of_old>();
            this.days_of_old2 = new HashSet<days_of_old2>();
            this.old = new HashSet<old>();
        }
    
        public int conoID { get; set; }
        public Nullable<double> age { get; set; }
        public Nullable<int> Level_of_functioningo { get; set; }
        public string gender { get; set; }
        public int idcity { get; set; }
        public string addressold { get; set; }
        public string languageold { get; set; }
        public Nullable<double> hanacha_and_money_for_hour { get; set; }
        public Nullable<long> passwardold { get; set; }
        public string mail { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<days_of_old> days_of_old { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<days_of_old2> days_of_old2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<old> old { get; set; }
    }
}
