//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class day_of_wor1
    {
        public int iddayw { get; set; }
        public Nullable<int> idwor { get; set; }
        public string dayw { get; set; }
        public Nullable<int> hourstartw { get; set; }
        public Nullable<int> hourendw { get; set; }
    
        public virtual Foreign_worker Foreign_worker { get; set; }
    }
}
