//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class days_of_wor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public days_of_wor()
        {
            this.Constraintsforeigenworkerne = new HashSet<Constraintsforeigenworkerne>();
        }
    
        public int iddayw { get; set; }
        public Nullable<int> idwor { get; set; }
        public string dayw { get; set; }
        public Nullable<int> hourstartw { get; set; }
        public Nullable<int> hourendw { get; set; }
        public Nullable<int> confid { get; set; }
        public Nullable<bool> isavliable { get; set; }
    
        public virtual Constraintsforeigenworker Constraintsforeigenworker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constraintsforeigenworkerne> Constraintsforeigenworkerne { get; set; }
        public virtual Foreign_worker Foreign_worker { get; set; }
    }
}
