//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class days_of_wor2
    {
        public int iddayw { get; set; }
        public Nullable<int> idwor { get; set; }
        public Nullable<bool> isSunday { get; set; }
        public Nullable<bool> isManday { get; set; }
        public Nullable<bool> isTuthday { get; set; }
        public Nullable<bool> isWenthday { get; set; }
        public Nullable<bool> isThursday { get; set; }
        public Nullable<bool> isFriday { get; set; }
        public Nullable<bool> isShabbat { get; set; }
        public Nullable<int> hourstartw { get; set; }
        public Nullable<int> hourendw { get; set; }
        public Nullable<int> confid { get; set; }
        public Nullable<bool> isavliable { get; set; }
    
        public virtual Constraintsforeigenworker Constraintsforeigenworker { get; set; }
        public virtual Foreign_worker Foreign_worker { get; set; }
    }
}
