//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foreign_worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Foreign_worker()
        {
            this.day_of_wor1 = new HashSet<day_of_wor1>();
            this.days_of_wor = new HashSet<days_of_wor>();
            this.days_of_wor2 = new HashSet<days_of_wor2>();
            this.Placement = new HashSet<Placement>();
        }
    
        public int idwor { get; set; }
        public string lnwor { get; set; }
        public string fnwor { get; set; }
        public int idcity { get; set; }
        public Nullable<int> confid { get; set; }
    
        public virtual city city { get; set; }
        public virtual Constraintsforeigenworker Constraintsforeigenworker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<day_of_wor1> day_of_wor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<days_of_wor> days_of_wor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<days_of_wor2> days_of_wor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Placement> Placement { get; set; }
    }
}
