//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<Constraintsforeigenworker> Constraintsforeigenworker { get; set; }
        public virtual DbSet<Constraintsforeigenworkerne> Constraintsforeigenworkerne { get; set; }
        public virtual DbSet<Constraintsold> Constraintsold { get; set; }
        public virtual DbSet<day_of_wor1> day_of_wor1 { get; set; }
        public virtual DbSet<days_of_old> days_of_old { get; set; }
        public virtual DbSet<days_of_old2> days_of_old2 { get; set; }
        public virtual DbSet<days_of_wor> days_of_wor { get; set; }
        public virtual DbSet<days_of_wor2> days_of_wor2 { get; set; }
        public virtual DbSet<Foreign_worker> Foreign_worker { get; set; }
        public virtual DbSet<old> old { get; set; }
        public virtual DbSet<Placement> Placement { get; set; }
    }
}
