//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int idPlacement { get; set; }
        public int idold { get; set; }
        public int idwor { get; set; }
        public Nullable<System.DateTime> Start_Datep { get; set; }
        public Nullable<System.DateTime> end_Datep { get; set; }
        public string nameold { get; set; }
        public string namewor { get; set; }
    
        public virtual Foreign_worker Foreign_worker { get; set; }
        public virtual old old { get; set; }
    }
}
